<p>This Privacy Policy governs the manner in which TrackMy Solutions collects, uses, maintains and discloses information collected from users (each, a "User") of the TrackMyImplants.com website ("Site"). This privacy policy applies to the Site and all products and services offered by TrackMy Solutions.</p>
<p><strong>Personal identification information</strong></p>
<p>We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, mailing address, phone number, credit card information. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>
<p><strong>Non-personal identification information</strong></p>
<p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>
<p>&nbsp;</p>
<p><strong>Disclaimer</strong></p>
<p>TrackMy Solutions (TrackMy Implants product) leverages openFDA and other APIs for information/data to offer up the best user experience possible. Do not rely on TrackMy Solutions products to make decisions regarding medical care, as our products are intended for informational purposes. Always speak to your health provider about the risks and benefits of using TrackMy Solutions products.</p>
<p>&nbsp;</p>
<p><strong>Web browser cookies</strong></p>
<p>Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>
<p><strong>How we use collected information</strong></p>
<p>TrackMy Solutions may collect and use Users personal information for the following purposes:</p>
<p>&nbsp;</p>
<ul>
<li>To improve customer service Information you provide helps us respond to your customer service requests and support needs more efficiently.</li>
<li>To process payments We may use the information Users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.</li>
<li>To run a promotion, contest, survey or other Site feature To send Users information they agreed to receive about topics we think will be of interest to them.</li>
<li>To send periodic emails We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests. If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, they may do so by contacting us via our Site.
<br>
To do research To advance our technology, it is helpful for us to share information we get from studying patient data. We do this by putting it into one or more databases, where it is stored along with information from other studies. We can then study the information combined from many studies to learn even more about health and outcomes. If you agree to use our technology, your health information will be placed into one or more databases, so that it may be used for future research on any topic and shared broadly for research purposes. A researcher who wants to study the information must apply to the database and be approved. Researchers with an approved study may be able to see and use de-identified information (we will never share your name, or personal contact information). We do not expect any direct benefits for you from research resulting in the use of any de-identified data. You may stop using our technology and withdraw permission for your individual data being de-identified/aggregated for use for future research at any time. If you choose, you may request to have your data destroyed. However, it may not be possible to withdraw or delete de-identified materials or data once we have been shared with other researchers.</li>
</ul>
<p><strong>Sharing your personal information</strong></p>
<p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.</p>
<p><br><strong>Release of Liability</strong></p>
<p>In consideration for being allowed to use TrackMy Solutions products, you release from liability and waive your right to sue TrackMy Solutions LLC, their employees, officers, volunteers and agents (collectively Company) from any and all claims, including claims of the Company's negligence, resulting in any physical injury, illness (including death) or economic loss you may suffer or which may result from your use of TrackMy Solutions products, or any events incidental to leveraging TrackMy Solutions products.</p>
<p>&nbsp;</p>
<p><strong>Expressed Assumption of Risk</strong></p>
<p>You are voluntarily using TrackMy Solutions technology (current beta version of our technology, that we are continuing to develop upon and enhance). While we do not anticipate any issues, you understand that there are risks associated with using this technology, such as the potential for physical and/or psychological injury, pain, suffering, illness, disfigurement, temporary or permanent disability, death or economic loss (assuming you do not take action on any relevant data around recalled/adverse event reporting). These injuries or outcomes may arise from my own or other's actions, inactions, or negligence. Nonetheless, I assume all risks of my use of this technology, whether known or unknown to me, or any events incidental to leveraging TrackMy Solutions products.</p>
<p>&nbsp;</p>
<p><strong>Hold Harmless Clause</strong></p>
<p>I agree to hold the Company harmless from any and all claims, loss or damage to my personal property, liabilities and costs, including attorney's fees, as a result of use of TrackMy Solutions technology or any events incidental to this Activity. If the Company incurs any of these types of expenses, you agree to reimburse the Company</p>
<p><strong>Medical Consent</strong></p>
<p>If you need medical treatment as a result of use of TrackMy technology, you agree to be financially responsible for any costs incurred as a result of such treatment. You are aware that the Company does not provide health insurance for you and that you should carry your own health insurance</p>
<p><strong>Minor Clause</strong></p>
<p>The use of TrackMy technology may be leverage for a minor. In this case, we capture power of attorney and notate use of the technology can be by the parent or legal guardian of the Participant. If this is the case, the parent/guardian will be accepting these terms. You have read this document, and are agreeing to it freely. I understand the legal consequences of agreeing this document, including (a) releasing the Company from all liability on my and the Participant's behalf, (b) waiving my and the Participants' right to sue the Company, (c) and assuming all risks of Participant's participation in using our technolology. You allow the Participant to participate in this Activity. I understand that you are responsible for the obligations and acts of the Participant as described in this document. You agree to be bound by the terms of this document</p>
<p><br><strong>Third party websites</strong></p>
<p>Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website's own terms and policies.</p>
<p><strong>Changes to this privacy policy</strong></p>
<p>TrackMy Solutions has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>
<p><strong>Your acceptance of these terms</strong></p>
<p>By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p>
<p>You have read this document, and you are agreeing it freely. You understand the legal consequences of agreeing this document, including (a) releasing the Company from all liability, (b) waiving your right to sue the Company, (c) and assuming all risks of using our technology</p>
<p><strong>Contacting us</strong></p>
<p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at: TrackMy Solutions 816-839-5610 info@TrackMyImplants.com</p>
<p>This document was last updated on October 2nd, 2018</p>
