<p><strong>Terms of Use</strong></p>
<p>TrackMy Solutions Agreement of Terms of Use. These terms apply to use of all TrackMy Solutions technology, initial product TrackMyImplants (in development form), a web application triggered from URL trackmyapp.us, here in referenced as TrackMyImplants</p>
<p>By visiting, using and/or submitting information to TrackMyImplants , you are accepting this Agreement of Terms of Use (this "Agreement") and our Privacy Policy.</p>
<p>This Agreement is made by and between TrackMy Solutions, a Missouri corporation ("TrackMy"), and you, a user of TrackMyImplants. This Agreement sets forth the terms and conditions that apply to your access and use of the Internet websites owned and operated by TrackMy and its affiliates, including, but not limited to, the website located at the URL TrackMyImplants ("TrackMyImplants"), and URL Trackmyapp.us.</p>
<p><strong>Applicability of this Agreement</strong></p>
<p>This Agreement is intended to apply to you, TrackMy, its affiliates and all Internet websites owned and operated by TrackMy and its affiliates, including, but not limited to, TrackMyImplants and trackmyapp.us .</p>
<p><strong>Your Right to Access and Use TrackMyImplants</strong></p>
<p>Your right to access and use TrackMyImplants is personal to you and is not transferable by you to any other person or entity. You are only entitled to access and use TrackMyImplants for lawful purposes and pursuant to the terms and conditions of this Agreement. Your access and use of TrackMyImplants may be interrupted from time to time for any of several reasons, including, but not limited to, the malfunction of TrackMy's equipment, periodic updating, maintenance or repair activities that TrackMy may undertake from time to time, or other actions that TrackMy, in its sole discretion, may elect to take. TrackMy reserves the right to suspend or discontinue the availability of TrackMyImplants for access and use at any time in its sole discretion and without prior notice to you.</p>
<p><strong>Disclaimer</strong></p>
<p>TrackMy Solutions (TrackMy Implants product) leverages openFDA and other APIs for information/data to offer up the best user experience possible. Do not rely on TrackMy Solutions products to make decisions regarding medical care, as our products are intended for informational purposes. Always speak to your health provider about the risks and benefits of using TrackMy Solutions products.</p>
<p><strong>Your Registration with TrackMyImplants</strong></p>
<p>Certain services and features of TrackMyImplants are accessible only to registered users. The rights to register with TrackMyImplants and to be issued a username or password by TrackMy are available only to those individuals who provide to TrackMy the requested accurate, complete and current personally identifiable information. You must inform TrackMy of any changes to or updates of any personally identifiable information that you provide to TrackMy. You can submit changes or updates to TrackMy via our contact form. TrackMy reserves the right to deny or revoke issuance of any username or password TrackMy issues, at any time and without prior notice.</p>
<p><strong>Your Compliance with this Agreement</strong></p>
<p>In order to determine your compliance with this Agreement, TrackMy may monitor your access and use of TrackMyImplants in accordance with TrackMy's Privacy Policy for TrackMyImplants . Any action by you that, in TrackMy's sole discretion, violates the terms and conditions of this Agreement, or restricts, inhibits or prevents any third party from accessing, using or enjoying TrackMyImplants , or through the use of TrackMyImplants , defames, abuses, harasses, offends or threatens any other user or third party, shall not be permitted, and may result in your loss of the right to access and use of TrackMyImplants .</p>
<p><strong>Your Transmissions, Submissions and Postings to TrackMyImplants</strong></p>
<p>If you transmit, submit or post information to TrackMyImplants that is not personally identifiable information, you automatically grant TrackMy the royalty-free, non-exclusive right and license to use, copy, format, adapt and publicly display such information (in whole or in part) worldwide, and/or to incorporate the same in other Content (defined below) and/or works in any form, media or technology now known or developed in the future. TrackMy may, in its sole discretion, edit, refuse to post or remove any information you transmit, submit or post to TrackMyImplants .</p>
<p>You shall not transmit, submit or post information to TrackMyImplants that contains any viruses, worms, Trojan horses, trap doors, back doors, easter eggs, time bombs, cancelbots or other code or computer programming routines that contain contaminating or destructive properties or that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information.</p>
<p><strong>TrackMy Development Clause/Data Upload</strong></p>
<p>Currently, TrackMyImplants is in development form. We are offering use of the technology currently yet are continuing to make changes and improvements to the product. In this current state, we may work with your Surgeon/Physician to exchange/add data to our database linked to your user account (ie&nbsp; a surgeon (or TrackMy) can upload device related data on your behalf into your user profile for recall/adverse event tracking). We make all efforts to ensure we are not exchanging any data inappropriately and have safeguards in place to ensure no data leakage.</p>
<p><strong>TrackMy Data Share</strong></p>
<p>With agreeing to these terms you allow TrackMy to share any data that we deem relevant (that has been entered either by yourself into our databases, or by us on your behalf) to improve any health-related outcomes, or personal related outcomes. The sharing of this data will be done in a secure format and may or may not eventually benefit you as a user (example&nbsp; should a recall happen, and we notify you, we may share this data with any relevant care team members to improve your care, or with resources like Attorneys that can work with you on any litigation potential needs).</p>
<p><strong>TrackMy's Intellectual Property Rights</strong></p>
<p>The names "TrackMy" and "TrackMyImplants" and the TrackMy and TrackMyImplants trademarks, logos and graphics are trademarks of TrackMy, and may not be used by you without the prior express written permission of TrackMy, which permission may be withheld in TrackMy's sole discretion.</p>
<p>The data and content viewable on, contained in, or downloadable from, TrackMyImplants , including, without limitation, the coursework available on TrackMyImplants (collectively, the "Content"), is copyrighted by TrackMy and/or other third parties. TrackMy also owns a copyright of a collective work in the selection, coordination, arrangement, presentation, display and enhancement of the Content. Viewing, reading, printing, downloading or otherwise using the Content does not entitle you to any ownership or intellectual property rights to the Content.</p>
<p>You shall be solely responsible for any damage resulting from your infringement of TrackMy's and other third parties' intellectual property rights regarding the "TrackMy" and "TrackMyImplants" names, the TrackMy and TrackMyImplants trademarks, logos and graphics, and/or the Content, and/or any other harm incurred by TrackMy or third parties as a direct or indirect result of your copying, distributing, redistributing, transmitting, publishing or using any of the same for purposes that are contrary to the terms and conditions of this Agreement.</p>
<p><strong>Framing, Linking and Metatagging TrackMyImplants</strong></p>
<p>You may not frame or utilize any framing techniques regarding TrackMyImplants and/or the Content. You may not link to TrackMyImplants without the express written permission of TrackMy. You may not use any metatags or any other hidden text utilizing TrackMy, TrackMyImplants or any of TrackMy's trademarks.</p>
<p><strong>Your Use of the Content</strong></p>
<p>Without the prior written consent of TrackMy, you may only print, download or otherwise use the Content in the form of: (i) one machine-readable copy; (ii) one backup copy; and (iii) one print copy, for your noncommercial use; provided, however, that you shall not delete any proprietary notices or materials with regard to the foregoing manifestations of the Content. Except as otherwise permitted under the copyright laws of the United States, no other copying, compilation, distribution, redistribution, transmission, publication or use of the Content, other than the non-commercial use of the Content as permitted by this Agreement, is permitted by you without the express prior written permission of TrackMy, which permission may be withheld in TrackMy's sole discretion.</p>
<p>TrackMy Makes No Representations or Warranties Regarding the Content or the Merchandise The Content is being provided to you on an "as-is" basis, and the merchandise sold on TrackMyImplants (the "Merchandise") is being sold on an "as-is" basis. TrackMy does not make any representations, warranties or guarantees, express or implied, regarding the accuracy, correctness, or completeness of the Content and/or the Merchandise, nor the safety, reliability, title, merchantability, conformity or fitness for a particular purpose of the Content and/or the Merchandise. It is your sole responsibility to independently evaluate the accuracy, correctness, completeness, safety and reliability of the Content and the Merchandise.</p>
<p>TrackMy makes no representation, warranty or guarantee that TrackMyImplants or the Content is free of infection from any viruses, worms, Trojan horses, trap doors, back doors, easter eggs, time bombs, cancelbots or other code or computer programming routines that contain contaminating or destructive properties or that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information.</p>
<p><strong>Other Features and Services Available Via TrackMyImplants</strong></p>
<p>Other features and services available via TrackMyImplants , including, without limitation, management of professional licensing requirements and reporting of professional licensing requirements to state licensing agencies, are provided for your convenience only. You are ultimately responsible to ensure that any service or other convenience provided by such features and services are ultimately performed, and performed in compliance with all laws, rules and regulations, including, without limitation, timeliness of submission or reporting. TrackMy shall in no event be liable for any penalties or damages that may occur as a result your access or use of, or reliance upon, any convenience features or services available via TrackMyImplants .</p>
<p><strong>Your Responsibility for Equipment and Related Costs</strong></p>
<p>You are responsible for obtaining and maintaining all telephone, computer hardware, Internet access services and other equipment or services needed to access and use TrackMyImplants , and all costs and fees associated with Internet access or long distance charges incurred with regard to your access and use of TrackMyImplants .</p>
<p><strong>Limitations on TrackMy's Liability</strong></p>
<p>TrackMy shall in no event be responsible to, or liable to, you, or any third party, whether in contract, warranty, tort (including negligence) or otherwise, for any damages, including, but not limited to, special, incidental, indirect or consequential damages that include, but are not limited to, damages for any loss of profit, revenue or business, as a direct or indirect result of: (i) your breach or violation of the terms and conditions of this Agreement; (ii) your access and use of TrackMyImplants and the access and use of TrackMyImplants under any username or password issued to you by TrackMy; (iii) your inability to access or use TrackMyImplants or any username or password issued to you by TrackMy; (iv) your downloading of any of the Content for your use; or (v) your reliance upon or use of the Content and/or the Merchandise. Use of the Content and/or the Merchandise is at your sole risk.</p>
<p>Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these state laws apply to you, some or all of the above limitations on TrackMy's liability may not apply to you, and you may have additional rights. The Merchandise purchased via TrackMyImplants is subject to a shipment contract. Risk of loss and title to the Merchandise passes to you pursuant to the carrier's shipment contract.</p>
<p><strong>Your Indemnification of TrackMy</strong></p>
<p>You shall defend, indemnify and hold harmless TrackMy and its officers, directors, shareholders, employees, independent contractors, agents, representatives and affiliates from and against all claims and expenses, including, but not limited to, attorneys' fees, arising out of, or attributable to: (i) any breach or violation of this Agreement by you; (ii) your failure to provide accurate, complete and current personally identifiable information requested pursuant to registration; (iii) your access or use of TrackMyImplants ; (iv) your access or use of TrackMyImplants under any username or password that may be issued to you by TrackMy; and/or (v) your use of the Content and/or the Merchandise.</p>
<p><strong>Amendments of this Agreement</strong></p>
<p>TrackMy reserves the right to amend this Agreement at any time in its sole discretion and without notice. Your right to access and use TrackMyImplants is subject only to our most current Agreement of Terms of Use. Changes, revisions or deletions with regard to this Agreement shall be effective immediately upon their inclusion in, or deletion from, this Agreement, and the posting of the same in this Agreement on TrackMyImplants .</p>
<p>You are advised and encouraged to visit TrackMyImplants on a regular basis to review our most current Agreement of Terms of Use, and review any changes that may have been made. Unless you elect to opt-out of this Agreement, you agree to be bound by our most current Agreement of Terms of Use, including any changes that have been made.</p>
<p>If at any time you wish to opt-out of this Agreement, please contact TrackMy via our contact form. However, keep in mind that your opting-out of this Agreement cancels your ability to access and use TrackMyImplants .</p>
<p><strong>TrackMy's Remedies</strong></p>
<p>You acknowledge that TrackMy may be irreparably damaged if this Agreement is not specifically enforced, and damages at law would be an inadequate remedy. Therefore, in the event of a breach or threatened breach of any provision of this Agreement by you, TrackMy shall be entitled, in addition to all rights and remedies, to an injunction restraining such breach or threatened breach, without being required to show any actual damage or to post an injunction bond, and/or to a decree for specific performance of the provisions of this Agreement.</p>
<p>For purposes of this Section, you agree that any action or proceeding with regard to such injunction restraining such breach or threatened breach shall be brought in the courts of record in Hillsborough County, Kansas. You consent to the jurisdiction of such courts and waive any objection to the laying of the venue of any such action or proceeding in such court. You agree that service of any court paper may be effected on such party by mail or in such other manner as may be provided under applicable laws, rules of procedure or local rules.</p>
<p><strong>Termination of this Agreement</strong></p>
<p>You may terminate or opt out of this Agreement at any time by contacting TrackMy via our contact form (or sending an email to info@trackmyimplants.com). Termination or opting out of this Agreement by you shall result in your loss of the right to access and use TrackMyImplants . Following your termination or opting out of this Agreement, the provisions of this Agreement regarding "Limitations of TrackMy's Liability," "Your Indemnification of TrackMy," "Governing Law and Arbitration" and "Miscellaneous" shall survive. TrackMy may terminate this Agreement or any usernames or passwords that may be issued to you, at any time, without prior notice, for any reason, or for no reason.</p>
<p><strong>Governing Law and Arbitration</strong></p>
<p>This Agreement is to be governed and construed in accordance with the internal laws of the State of Kansas, without regard for principles of conflicts of laws. Any civil action, claim, dispute or proceeding arising out of or relating to this Agreement, except for an injunctive action regarding a breach or threatened breach of any provision of this Agreement by you, shall be referred to final and binding arbitration, before a single arbitrator, under the commercial arbitration rules of the American Arbitration Association in Hillsborough County, Kansas. The arbitrator shall be selected by you and TrackMy, and if you and TrackMy are unable to reach agreement on selection of the arbitrator within thirty (30) days after the notice of arbitration is served, then the arbitrator shall be selected by the American Arbitration Association.</p>
<p>Judgment upon any award rendered by the arbitrator shall be final, binding and conclusive upon you and TrackMy and your and TrackMy's respective administrators, executors, legal representatives, successors and assigns, and may be entered in any court of competent jurisdiction. Notwithstanding the previous sentence, in no event shall either you or TrackMy be entitled to punitive, special, indirect or consequential damages and both you and TrackMy hereby waive your and TrackMy's respective rights to any punitive, special, indirect or consequential damages, including, but not limited to, damages for any loss of profit, revenue or business.</p>
<p><strong>Miscellaneous</strong></p>
<p>If any portion of this Agreement is deemed unlawful, void or unenforceable by any arbitrator or court of competent jurisdiction, this Agreement as a whole shall not be deemed unlawful, void or unenforceable, but only that portion of this Agreement that is unlawful, void or unenforceable shall be stricken from this Agreement.</p>
<p>The headings contained in this Agreement are for convenience of reference only, are not to be considered a part of this Agreement, and shall not limit or otherwise affect in any way the meaning or interpretation of this Agreement.</p>
<p>All covenants, agreements, representations and warranties made in this Agreement, as may be amended by TrackMy from time to time, shall survive your acceptance of this Agreement and the termination of this Agreement. This Agreement represents the entire understanding and agreement between you and TrackMy regarding the subject matter of this Agreement, and supersedes all other previous agreements, understandings and/or representations regarding the same.</p>